trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello, checkout mlpack/mlboard!"
  displayName: 'Initial ci config.'
