#include <cmath>
#include <utility>
#include <iostream>
#include <string>
#include <sstream>
#include <queue>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <fstream>
#include <queue>
#include <chrono> 
#include <ctime> 
#include <iostream>
#include <stdio.h>
#include <cstdint>
#include <cstring>
